global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus 자체

  - job_name: "backend"
    static_configs:
      - targets: ["backend:3000"] # backend 컨테이너
